package io.github.superfive666.duosdk.params.request;

import io.github.superfive666.duosdk.params.DuoAuthenticationMode;
import lombok.Getter;
import lombok.Setter;

/**
 * Parameters for /auth api
 * <a href="https://duo.com/docs/authapi#/auth">DUO #auth</a>
 * @author superfive
 */
@Getter
@Setter
public class Auth {
    /**
     * Permanent, unique identifier for the user as generated by Duo upon user creation (e.g. DUYHV6TJBC3O4RITS1WC).
     * Exactly one of user_id or username must be specified.
     */
    private String userId;
    /**
     * Unique identifier for the user that is commonly specified by your application during user creation
     * (e.g. user@domain.com). This value may also represent a username alias assigned to a user.
     *
     * Exactly one of user_id or username must be specified.
     */
    private String username;
    /**
     * Factor to use for authentication
     */
    private DuoAuthenticationMode factor;
    /**
     * The IP address of the user to be authenticated, in dotted quad format. This will cause an "allow"
     * response to be sent if appropriate for requests from a trusted network.
     */
    private String ipaddr;
    /**
     * The host name of the device accessing the application.
     */
    private String hostname;
    /**
     * If this parameter is not provided, then the /auth endpoint will only return a response when the authentication
     * process has completed. If, however, your application provides this parameter with a value of "1", then /auth
     * will immediately return a transaction ID, and your application will need to subsequently query the /auth_status
     * endpoint to get the status (and, eventually, result) of the authentication process.
     *
     * If you enable async, then your application will be able to retrieve real-time status updates from the
     * authentication process, rather than receiving no information until the process is complete.
     */
    private boolean async;
    /**
     * Additional API parameters depending on the mode of authentication factor
     */
    private DuoAuthApiParam additionalParam;
}
