package io.github.superfive666.duosdk.params.request;

import lombok.Getter;
import lombok.Setter;

/**
 * Parameters for /preauth api
 * <a href="https://duo.com/docs/authapi#/preauth">DUO #preauth</a>
 * @author superfive
 */
@Getter
@Setter
public class PreAuth {
    /**
     * Permanent, unique identifier for the user as generated by Duo upon user creation (e.g. DUYHV6TJBC3O4RITS1WC).
     *
     * Exactly one of user_id or username must be specified.
     */
    private String userId;

    /**
     * Unique identifier for the user that is commonly specified by your application during user creation
     * (e.g. user@domain.com). This value may also represent a username alias assigned to a user
     *
     * Exactly one of user_id or username must be specified.
     */
    private String username;

    /**
     * The IP address of the user to be authenticated, in dotted quad format. This will cause an "allow" response
     * to be sent if appropriate for requests from a trusted network.
     */
    private String ipaddr;

    /**
     * The host name of the device accessing the application.
     */
    private String hostname;

    /**
     * If the trusted_device_token is present and the <b>Remembered Devices</b> option is enabled in the Duo Admin Panel,
     * return an "allow" response for the period of time a device may be remembered as set by the Duo administrator.
     */
    private String trustedDeviceToken;
}
